import os
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from datetime import datetime

# --- COLOR PALETTE (Enterprise UI) ---
PRIMARY_BLUE = RGBColor(30, 41, 59)     # #1e293b (Dark Slate)
ACCENT_INDIGO = RGBColor(79, 70, 229)   # #4f46e5 (Indigo)
SUCCESS_GREEN = RGBColor(16, 185, 129)  # #10b981 (Emerald)
WARNING_RED = RGBColor(239, 68, 68)     # #ef4444 (Red)
LIGHT_BG = RGBColor(241, 245, 249)      # #f1f5f9 (Light Gray)
WHITE = RGBColor(255, 255, 255)

def style_table_header(cell, text, bg_color):
    """Helper to style table headers with background color and white bold text."""
    cell.text = text
    cell.fill.solid()
    cell.fill.fore_color.rgb = bg_color
    for paragraph in cell.text_frame.paragraphs:
        paragraph.alignment = PP_ALIGN.CENTER
        for run in paragraph.runs:
            run.font.bold = True
            run.font.color.rgb = WHITE
            run.font.size = Pt(12)

def style_table_cell(cell, text, font_size=11, bold=False, color=PRIMARY_BLUE):
    """Helper to style standard table cells with perfect alignment."""
    cell.text = text
    cell.text_frame.word_wrap = True
    for paragraph in cell.text_frame.paragraphs:
        for run in paragraph.runs:
            run.font.size = Pt(font_size)
            run.font.bold = bold
            run.font.color.rgb = color

def add_custom_title(slide, text):
    """Creates a standardized, perfectly aligned bold title for every slide."""
    txBox = slide.shapes.add_textbox(Inches(0.5), Inches(0.4), Inches(9), Inches(0.8))
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    p.text = text.upper()
    p.font.bold = True
    p.font.size = Pt(28)
    p.font.color.rgb = PRIMARY_BLUE
    return txBox

def generate_strategy_pptx(doc, output_path):
    """Generates an Enterprise-grade PowerPoint presentation from AI strategy data."""
    prs = Presentation()
    
    # We use Layout 6 (Blank) for EVERYTHING to prevent PowerPoint's default formatting from overlapping
    layout_blank = prs.slide_layouts[6] 

    # ==========================================
    # SLIDE 1: COVER SLIDE
    # ==========================================
    cover_slide = prs.slides.add_slide(layout_blank)
    
    banner = cover_slide.shapes.add_shape(1, Inches(0), Inches(0), Inches(10), Inches(1.5)) 
    banner.fill.solid()
    banner.fill.fore_color.rgb = ACCENT_INDIGO
    banner.line.fill.background()
    
    txBox = cover_slide.shapes.add_textbox(Inches(1), Inches(2.5), Inches(8), Inches(1.5))
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    p.text = "STRATEGIC ANALYSIS REPORT"
    p.font.bold = True
    p.font.size = Pt(36)
    p.font.color.rgb = PRIMARY_BLUE
    
    p2 = tf.add_paragraph()
    p2.text = f"Document: {doc.get('filename', 'Unknown')}"
    p2.font.size = Pt(18)
    p2.font.color.rgb = ACCENT_INDIGO

    txBox_footer = cover_slide.shapes.add_textbox(Inches(1), Inches(5.5), Inches(8), Inches(1))
    tf_footer = txBox_footer.text_frame
    tf_footer.text = f"Generated by: StrategixAI Enterprise Engine\nDate: {datetime.now().strftime('%B %d, %Y')}\nStrictly Confidential"
    for para in tf_footer.paragraphs:
        para.font.size = Pt(12)
        para.font.color.rgb = RGBColor(100, 116, 139)

    # ==========================================
    # SLIDE 2: 1. EXECUTIVE SUMMARY
    # ==========================================
    slide2 = prs.slides.add_slide(layout_blank)
    add_custom_title(slide2, "1. Executive Summary & Dashboard")

    tx_summary = slide2.shapes.add_textbox(Inches(0.5), Inches(1.3), Inches(9), Inches(2.5))
    tx_summary.text_frame.word_wrap = True
    p = tx_summary.text_frame.paragraphs[0]
    p.text = doc.get('summary', 'No summary available.')[:800] + ("..." if len(doc.get('summary', '')) > 800 else "")
    p.font.size = Pt(14)
    p.font.color.rgb = PRIMARY_BLUE

    tx_focus = slide2.shapes.add_textbox(Inches(0.5), Inches(4.5), Inches(9), Inches(0.5))
    tx_focus.text_frame.text = "Strategic Focus Areas & Indicators:"
    tx_focus.text_frame.paragraphs[0].font.bold = True
    
    focus_areas = ['GROWTH', 'EFFICIENCY', 'RISK', 'DIGITAL']
    colors = [ACCENT_INDIGO, SUCCESS_GREEN, WARNING_RED, RGBColor(245, 158, 11)] 
    
    for i, area in enumerate(focus_areas):
        shape = slide2.shapes.add_shape(1, Inches(0.5 + (i*2.2)), Inches(5.0), Inches(2), Inches(0.8))
        shape.fill.solid()
        shape.fill.fore_color.rgb = colors[i]
        shape.line.fill.background()
        tf = shape.text_frame
        tf.text = area
        tf.paragraphs[0].alignment = PP_ALIGN.CENTER
        tf.paragraphs[0].runs[0].font.bold = True
        tf.paragraphs[0].runs[0].font.color.rgb = WHITE

    sentiment = doc.get('sentiment', 'Neutral')
    tx_sent = slide2.shapes.add_textbox(Inches(0.5), Inches(6.0), Inches(9), Inches(0.5))
    p = tx_sent.text_frame.paragraphs[0]
    
    # First part: The standard label
    run1 = p.add_run()
    run1.text = "Overall AI Sentiment: "
    run1.font.bold = True
    run1.font.color.rgb = PRIMARY_BLUE
    
    # Second part: The highlighted sentiment value
    run2 = p.add_run()
    run2.text = str(sentiment)
    run2.font.bold = True
    run2.font.color.rgb = ACCENT_INDIGO  # This applies the nice Indigo theme color to the answer!
    
    # ==========================================
    # SLIDE 3: 2. SWOT ANALYSIS
    # ==========================================
    slide3 = prs.slides.add_slide(layout_blank)
    add_custom_title(slide3, "2. SWOT Analysis")
    
    swot = doc.get('swot', {})
    table_swot = slide3.shapes.add_table(2, 2, Inches(0.5), Inches(1.3), Inches(9), Inches(5.5)).table
    
    quadrants = [
        (0, 0, 'STRENGTHS', swot.get('strengths', []), SUCCESS_GREEN),
        (0, 1, 'WEAKNESSES', swot.get('weaknesses', []), WARNING_RED),
        (1, 0, 'OPPORTUNITIES', swot.get('opportunities', []), ACCENT_INDIGO),
        (1, 1, 'THREATS', swot.get('threats', []), RGBColor(245, 158, 11))
    ]
    
    for row, col, title, items, color in quadrants:
        cell = table_swot.cell(row, col)
        cell.text = f"{title}\n"
        cell.text_frame.paragraphs[0].font.bold = True
        cell.text_frame.paragraphs[0].font.color.rgb = color
        for item in items[:4]: 
            p = cell.text_frame.add_paragraph()
            p.text = f"• {item}"
            p.font.size = Pt(12)
            p.font.color.rgb = PRIMARY_BLUE

    # ==========================================
    # SLIDE 4: 3. PESTLE ANALYSIS
    # ==========================================
    slide4 = prs.slides.add_slide(layout_blank)
    add_custom_title(slide4, "3. Environmental Scan (PESTLE)")
    
    pestle = doc.get('pestle', {})
    if not pestle:
        tx = slide4.shapes.add_textbox(Inches(1), Inches(3), Inches(8), Inches(1))
        tx.text_frame.text = "No PESTLE data available."
    else:
        pestle_items = list(pestle.items())[:5]
        table_p = slide4.shapes.add_table(len(pestle_items) + 1, 2, Inches(0.5), Inches(1.3), Inches(9), Inches(5.5)).table
        table_p.columns[0].width = Inches(2.0)
        table_p.columns[1].width = Inches(7.0)
        
        style_table_header(table_p.cell(0, 0), "Macro Factor", ACCENT_INDIGO)
        style_table_header(table_p.cell(0, 1), "Strategic Assessment", ACCENT_INDIGO)
        
        row_idx = 1
        for key, val in pestle_items:
            style_table_cell(table_p.cell(row_idx, 0), str(key).upper(), 12, bold=True)
            style_table_cell(table_p.cell(row_idx, 1), str(val), 12)
            row_idx += 1

    # ==========================================
    # DYNAMIC SLIDES: 4. EXECUTION ROADMAP
    # ==========================================
    roadmap = doc.get("execution_roadmap", [])
    
    if not roadmap:
        slide_empty = prs.slides.add_slide(layout_blank)
        add_custom_title(slide_empty, "4. Step-by-Step Execution Roadmap")
        tx = slide_empty.shapes.add_textbox(Inches(1), Inches(3), Inches(8), Inches(1))
        tx.text_frame.text = "No Roadmap generated yet. Generate it in the web dashboard first."
    else:
        # 🚀 NEW LOGIC: Flatten the roadmap into individual rows, NOT phases.
        flat_steps = []
        for phase in roadmap:
            phase_info = f"{phase.get('phase', 'Phase')}\nFocus: {phase.get('focus', '')}"
            for i, step in enumerate(phase.get('steps', [])):
                flat_steps.append({
                    "phase_display": phase_info if i == 0 else "", # Only show phase name on the first row of that phase
                    "what": step.get('what', ''),
                    "why": step.get('why', ''),
                    "how": step.get('how', '')
                })
        
        # 🚀 STRICT LIMIT: Maximum 4 rows per slide ensures it NEVER overflows
        MAX_ROWS_PER_SLIDE = 4
        chunks = [flat_steps[i:i + MAX_ROWS_PER_SLIDE] for i in range(0, len(flat_steps), MAX_ROWS_PER_SLIDE)]
        
        for idx, chunk in enumerate(chunks):
            slide_roadmap = prs.slides.add_slide(layout_blank)
            
            title_text = "4. Step-by-Step Execution Roadmap"
            if len(chunks) > 1:
                title_text += f" (Part {idx + 1})"
            
            add_custom_title(slide_roadmap, title_text)
            
            # Create table strictly sized to the chunk length
            total_rows = len(chunk) + 1
            table_r = slide_roadmap.shapes.add_table(total_rows, 3, Inches(0.5), Inches(1.3), Inches(9), Inches(5.0)).table
            
            # Adjusted column widths
            table_r.columns[0].width = Inches(2.3)
            table_r.columns[1].width = Inches(3.7)
            table_r.columns[2].width = Inches(3.0)
            
            style_table_header(table_r.cell(0, 0), "Phase & Focus", PRIMARY_BLUE)
            style_table_header(table_r.cell(0, 1), "Action (What & Why)", PRIMARY_BLUE)
            style_table_header(table_r.cell(0, 2), "Success Metric (How)", PRIMARY_BLUE)
            
            for r_idx, step_data in enumerate(chunk, start=1):
                if step_data["phase_display"]:
                    style_table_cell(table_r.cell(r_idx, 0), step_data["phase_display"], 10, bold=True)
                else:
                    style_table_cell(table_r.cell(r_idx, 0), "", 10)
                    
                action_text = f"WHAT: {step_data['what']}\nWHY: {step_data['why']}"
                style_table_cell(table_r.cell(r_idx, 1), action_text, 10)
                
                metric_text = f"📈 {step_data['how']}"
                style_table_cell(table_r.cell(r_idx, 2), metric_text, 10)

    # ==========================================
    # FINAL SLIDE: 5. CRITICAL RISK MANAGEMENT
    # ==========================================
    slide_risk = prs.slides.add_slide(layout_blank)
    add_custom_title(slide_risk, "5. Critical Risk Management")
    
    threats = doc.get('swot', {}).get('threats', [])
    
    if not threats:
        tx = slide_risk.shapes.add_textbox(Inches(1), Inches(3), Inches(8), Inches(1))
        tx.text_frame.text = "No critical risks detected."
    else:
        num_rows = min(len(threats), 5) + 1
        table_risk = slide_risk.shapes.add_table(num_rows, 2, Inches(1.0), Inches(1.5), Inches(8), Inches(4)).table
        table_risk.columns[0].width = Inches(5.5)
        table_risk.columns[1].width = Inches(2.5)
        
        style_table_header(table_risk.cell(0, 0), "Identified Risk Factor (Threats)", WARNING_RED)
        style_table_header(table_risk.cell(0, 1), "Impact Assessment", WARNING_RED)
        
        for i, threat in enumerate(threats[:5]):
            style_table_cell(table_risk.cell(i+1, 0), threat, 12)
            
            cell_impact = table_risk.cell(i+1, 1)
            cell_impact.text = "HIGH IMPACT"
            cell_impact.text_frame.paragraphs[0].alignment = PP_ALIGN.CENTER
            cell_impact.text_frame.paragraphs[0].runs[0].font.bold = True
            cell_impact.text_frame.paragraphs[0].runs[0].font.color.rgb = WARNING_RED

    prs.save(output_path)
    return True